### PR TITLE
Revert "Fix Example 3, repeated frame grabbing"

### PR DESCRIPTION
**Pull request by gmandyam**
Reverts w3c/mediacapture-image#65.  Example 3 declarative syntax does not display properly.

### CODE REVIEW

**Comment by gmandyam** [comment]
@dandv Please correct and resubmit PR.

**Comment by dandv** [comment]
@gmandyam, can you please clarify on

> Example 3 declarative syntax does not display properly.

My PR executes fine in Chrome 55, whereas the previous example didn't run at all.

Also, if you have a minute, could you add some information to your GitHub profile, since you're a W3C group member? Thanks.

**Comment by dandv** [comment]
@miguelao, any ideas?

**Comment by gmandyam** [comment]
@dandv I have no doubt the example executed properly in Chrome.  The problem was that the text you submitted in the PR was not rendering properly due to what I would imagine was some Respec issue.  When I said "declarative syntax" I meant that the HTML markup (https://en.wikipedia.org/wiki/Declarative_programming) parts of the example were not displaying properly in the final document text.

**Comment by dandv** [comment]
> The problem was that the text you submitted in the PR was not rendering properly

Would you be kind enough to provide a screenshot, or instruction on how to obtain the same display? (The latter could go in the README.)

**Pull request merged**
