### PR TITLE
Clarify pan/tilt/zoom settings (#245)

### PR DESCRIPTION
**Pull request by eehakkin**
Split from https://github.com/w3c/mediacapture-image/pull/248 per @youennf's request.

### CODE REVIEW

**Comment by beaufortfrancois** [comment]
Following https://github.com/w3c/mediacapture-image/pull/248#discussion_r473096602,

Web developers can already monitor the camera with PTZ permission with the permissions API to detect changes.

```js
const panTiltZoomPermissionStatus = await navigator.permissions.query({
  name: "camera",
  panTiltZoom: true,
});

if (panTiltZoomPermissionStatus.state == "granted") {
  // User has granted access to this website to control camera PTZ.
}

panTiltZoomPermissionStatus.onchange = () => {
  // User has changed PTZ permission status.
}
```

**Comment by beaufortfrancois** [comment]
@youennf (gentle ping)

**Comment by youennf** [comment]
As I read it, this looks fine, though I would like to get some clarification to https://github.com/w3c/mediacapture-image/pull/250#issuecomment-680868777.

**Comment by beaufortfrancois** [comment]
@youennf Does it look good to you with recent changes around ideal PTZ constraints only in getUserMedia?

**Review by youennf — APPROVED** [review]
LGTM

**Pull request merged**
