### PR TITLE
Update Image Capture polyfill

### PR DESCRIPTION
**Pull request by FluorescentHallucinogen**
***

### :boom: Error: 500 Internal Server Error :boom: ###

[PR Preview](https://github.com/tobie/pr-preview#pr-preview) failed to build. _(Last tried on Feb 20, 2023, 3:03 PM UTC)_.

<details>
<summary>More</summary>

PR Preview relies on a number of web services to run. There seems to be an issue with the following one:

:rotating_light: [CSS Spec Preprocessor](https://api.csswg.org/bikeshed/) - CSS Spec Preprocessor is the web service used to build Bikeshed specs.

:link: [Related URL](https://api.csswg.org/bikeshed/?url=https%3A%2F%2Fraw.githubusercontent.com%2FFluorescentHallucinogen%2Fmediacapture-image%2F3cbf00cde13f698dc069fafc450b477367cfad37%2Findex.bs&force=1&md-warning=not%20ready)

```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>500 Internal Server Error</title>
</head><body>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error or
misconfiguration and was unable to complete
your request.</p>
<p>Please contact the server administrator at 
 [no address given] to inform them of the time this error occurred,
 and the actions you performed just before this error.</p>
<p>More information about this error may be available
in the server error log.</p>
<hr>
<address>Apache/2.4.10 (Debian) Server at api.csswg.org Port 443</address>
</body></html>

```

_If you don't have enough information above to solve the error by yourself (or to understand to which web service the error is related to, if any), please [file an issue](https://github.com/tobie/pr-preview/issues/new?title=Error%20not%20surfaced%20properly&body=See%20w3c/mediacapture-image%23299.)._
</details>

### CODE REVIEW

**Comment by riju** [comment]
Thanks @FluorescentHallucinogen  ! 

@beaufortfrancois : Do you have some plans to merge https://googlechrome.github.io/samples/image-capture/ and  https://github.com/GoogleChromeLabs/imagecapture-polyfill ?

**Comment by FluorescentHallucinogen** [comment]
@riju
> Do you have some plans to merge https://googlechrome.github.io/samples/image-capture/ and https://github.com/GoogleChromeLabs/imagecapture-polyfill

What do you mean? The first is a set of demos (samples) and the second is a polyfill. 🤔

**Comment by FluorescentHallucinogen** [comment]
Also, I know good https://beaufortfrancois.github.io/sandbox/image-capture/playground.html and https://ptz.glitch.me samples. )

**Comment by FluorescentHallucinogen** [comment]
And, of course, https://github.com/riju/WebCamera. But it would be really nice to combine all these demos (samples) into one full-featured sample. )

**Comment by FluorescentHallucinogen** [comment]
And a very cool demo for torch:

https://gk-simple-torch.web.app
https://github.com/gkalpak/simple-torch

Sorry for offtop, but maybe we need to create a new special page with list of cool demos that use Image Capture API? )

But, again, most of them could be combined into one big demo. :)

**Comment by beaufortfrancois** [comment]
Thank you @FluorescentHallucinogen for the PR!

https://googlechrome.github.io/samples/image-capture/ and https://github.com/GoogleChromeLabs/imagecapture-polyfill are two different things. We should not merge them.

> We should add an .md or some such in the spec repo with these links (if the authors have given explicit consent). It helps to showcase the usage of ImageCapture API in the real world.

+1

**Pull request merged**
